// vim: fdc=4
//using System.Collections;
using System.Collections.Generic;
using UnityEngine;


[RequireComponent(typeof(LSystem))]
public class Bush : MonoBehaviour {
    LSystem lsystem;

    void Awake() {
        lsystem = GetComponent<LSystem>();

        lsystem.axiom = new List<Instruction>() {
            new Instruction("$"),
            new Instruction("S"),
            new Instruction("A")
        };

        lsystem.rules = new List<Rule>() {
            new Rule(0.34f, "A", _ => new List<Instruction>() {
                new Instruction("["),
                new Instruction("&"),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("["),
                new Instruction("&"),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("["),
                new Instruction("&"),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("B"),
                new Instruction("A"),
                new Instruction("]"),
            }),
            new Rule(0.33f, "A", _ => new List<Instruction>() {
                new Instruction("["),
                new Instruction("&"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("["),
                new Instruction("&"),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("["),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("B"),
                new Instruction("A"),
                new Instruction("]"),
            }),
            new Rule(0.33f, "A", _ => new List<Instruction>() {
                new Instruction("["),
                new Instruction("&"),
                new Instruction("F"),
                new Instruction("%"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("["),
                new Instruction("&"),
                new Instruction("L"),
                new Instruction("A"),
                new Instruction("]"),
            }),
            new Rule(1, "F", _ => new List<Instruction>() {
                new Instruction("S"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("/"),
                new Instruction("F"),
            }),
            new Rule(1, "S", _ => new List<Instruction>() {
                new Instruction("F"),
                new Instruction("L"),
            }),
            new Rule(1, "L", _ => new List<Instruction>() {
                new Instruction("["),
                new Instruction("1"),
                new Instruction("^"),
                new Instruction("^"),
                new Instruction("{"),
                new Instruction("-"),
                new Instruction("f"),
                new Instruction("+"),
                new Instruction("f"),
                new Instruction("+"),
                new Instruction("f"),
                new Instruction("-"),
                new Instruction("+", Mathf.PI),
                new Instruction("-"),
                new Instruction("f"),
                new Instruction("+"),
                new Instruction("f"),
                new Instruction("+"),
                new Instruction("f"),
                new Instruction("}"),
                new Instruction("]"),
            }),
        };
    }
}
